const assert = require('node:assert/strict');
const fs = require('node:fs');
module.exports = async ({command,evaluate,waitFor,reloadPage}) => {
    await command('Emulation.setDeviceMetricsOverride',{width:1280,height:900,deviceScaleFactor:1,mobile:false});
    const reader=`window.readGridSlot = () => new Promise(resolve=>{const r=indexedDB.open('gazeTrackerSaves');r.onsuccess=()=>{const db=r.result;const q=db.transaction('slots').objectStore('slots').get(2);q.onsuccess=()=>{resolve(q.result);db.close()}}});`;
    await evaluate(`${reader} (async()=>{
        const scene=await readGridSlot();const base=scene.objects[0];
        scene.objects=Array.from({length:5},(_,i)=>({...base,id:'grid-test-'+i,x:40+i*30,y:40,width:160,height:80,animationType:null,zIndex:i}));
        Object.assign(scene.objects[3],{type:'shape',shapeType:'rect',color:'#ff3366'});
        Object.assign(scene.objects[4],{type:'text',text:'A long label to fit in a grid cell',size:40,color:'#ffffff',fontFamily:'sans-serif',fontWeight:'normal',fontStyle:'normal'});
        Object.assign(scene,{currentGrid:null,showGuides:true,enableAutoSnap:true,canvasZoom:.5,canvasPanX:20,canvasPanY:20});
        await new Promise(resolve=>{const r=indexedDB.open('gazeTrackerSaves');r.onsuccess=()=>{const db=r.result;const t=db.transaction('slots','readwrite');t.objectStore('slots').put(scene);t.oncomplete=()=>{db.close();resolve()}}});
        document.querySelector('.save-slot__btn--load[data-slot="2"]').click();
    })()`);
    await waitFor(`document.querySelectorAll('#layer-list > *').length===5`);
    const save = async()=>{
        await evaluate(`${reader} (async()=>{window.gridSaveBefore=(await readGridSlot()).savedAt;document.querySelector('.save-slot__btn--save[data-slot="2"]').click()})()`);
        await waitFor(`readGridSlot().then(s=>s.savedAt!==gridSaveBefore)`); return evaluate(`readGridSlot()`);
    };
    await evaluate(`document.getElementById('grid-4').click();document.getElementById('grid-4').click()`);
    assert.equal(await evaluate(`document.getElementById('grid-4').getAttribute('aria-pressed')`),'true');
    assert.ok(await evaluate(`document.getElementById('grid-summary').textContent.includes('1 will stay')`));
    await evaluate(`document.getElementById('grid-suggest-layout').click()`);
    assert.equal(await evaluate(`document.getElementById('grid-6').getAttribute('aria-pressed')`),'true');
    await evaluate(`document.getElementById('arrange-text-boxes').click();document.getElementById('arrange-shapes').click();document.getElementById('grid-4').click();document.getElementById('grid-fit-targets').click()`);
    const before = await save();
    await evaluate(`document.getElementById('arrange-all-targets').click()`);
    const placed = await save();
    assert.deepEqual(placed.objects.slice(0,3).map(o=>[o.x+o.width/2,o.y+o.height/2]),[[480,270],[1440,270],[480,810]]);
    assert.deepEqual(placed.objects.slice(0,3).map(o=>[o.width,o.height]),before.objects.slice(0,3).map(o=>[o.width,o.height]));
    assert.deepEqual(placed.objects.slice(3),before.objects.slice(3),'Excluded text and shapes remain unchanged');
    await evaluate(`document.getElementById('undo-btn').click()`);
    assert.deepEqual((await save()).objects,before.objects,'One Undo restores the entire arrangement, including shape geometry');
    await evaluate(`document.getElementById('redo-btn').click()`);
    assert.deepEqual((await save()).objects,placed.objects);
    console.log('PASS: grid selection stays selected, capacity suggestion works, exclusions and keep-size work, arrangement undoes/redoes');
    await evaluate(`document.getElementById('arrange-text-boxes').click();document.getElementById('arrange-shapes').click();document.getElementById('grid-6').click();document.getElementById('grid-fit-targets').click();document.getElementById('arrange-all-targets').click();document.getElementById('enable-auto-snap').click();document.getElementById('show-position-guides').click()`);
    const fitted = await save();
    for(const obj of fitted.objects) { assert.ok(obj.width<=512.1);assert.ok(obj.height<=432.1); }
    await reloadPage();
    await waitFor(`document.querySelector('.save-slot__btn--load[data-slot="2"]')`);
    await evaluate(`document.getElementById('splash-close-btn').click();document.querySelector('.save-slot__btn--load[data-slot="2"]').click()`);
    await waitFor(`document.querySelectorAll('#layer-list > *').length===5`);
    assert.equal(await evaluate(`document.getElementById('grid-6').getAttribute('aria-pressed')`),'true');
    assert.equal(await evaluate(`document.getElementById('enable-auto-snap').checked`),false);
    assert.equal(await evaluate(`document.getElementById('show-position-guides').checked`),false);
    assert.deepEqual((await save()).objects,fitted.objects);
    await waitFor(`!document.getElementById('splash-screen-overlay')`);
    await evaluate(`for (const [drawer, handle] of [['controls-drawer','toggle-controls-btn'],['media-library','toggle-library-btn']]) { if (document.getElementById(drawer).classList.contains('open')) document.getElementById(handle).click(); }`);
    await new Promise(r=>setTimeout(r,350));
    const obj=fitted.objects[0], box=await evaluate(`(()=>{const r=document.getElementById('canvas-container').getBoundingClientRect();return {x:r.x,y:r.y}})()`);
    const x=box.x+(obj.x+obj.width/2)*fitted.canvasZoom+fitted.canvasPanX, y=box.y+(obj.y+obj.height/2)*fitted.canvasZoom+fitted.canvasPanY;
    for(const [type,dx,buttons] of [['mousePressed',0,1],['mouseMoved',20,1],['mouseReleased',20,0]]) await command('Input.dispatchMouseEvent',{type,x:x+dx,y,button:'left',buttons,clickCount:1});
    await new Promise(r=>setTimeout(r,250));
    const dragged=await save();assert.ok(Math.abs(dragged.objects[0].x-obj.x-20/fitted.canvasZoom)<.1,'Snap off must not snap on release');
    assert.equal(await evaluate(`document.getElementById('show-position-guides').checked`),false);
    await evaluate(`document.getElementById('toggle-library-btn').click();document.getElementById('grids-panel').scrollIntoView({block:'end',behavior:'instant'})`);
    await new Promise(r=>setTimeout(r,350));
    await command('Page.captureScreenshot').then(r=>fs.writeFileSync(require('./screenshot-path.cjs')('grid-desktop.png'),Buffer.from(r.data,'base64')));
    await command('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
    await evaluate(`document.getElementById('grids-panel').scrollIntoView({block:'end',behavior:'instant'})`);
    await new Promise(r=>setTimeout(r,350));
    assert.ok(await evaluate(`Array.from(document.querySelectorAll('.grid-choice')).every(el=>{const r=el.getBoundingClientRect();return r.width>=75&&r.height>=75&&r.left>=0&&r.right<=innerWidth})`));
    await command('Page.captureScreenshot').then(r=>fs.writeFileSync(require('./screenshot-path.cjs')('grid-mobile.png'),Buffer.from(r.data,'base64')));
    await evaluate(`document.getElementById('mode-opt-play').click()`);
    assert.equal(await evaluate(`document.getElementById('arrange-all-targets').disabled`),true);
    assert.ok(await evaluate(`Array.from(document.querySelectorAll('.grid-choice')).every(b=>b.disabled)`));
    console.log('PASS: fitted targets and grid settings reload correctly; snap off and hidden guides stay off; mobile layouts and Play protection work');
};
