const assert = require('node:assert/strict');
const fs = require('node:fs');
module.exports = async ({ command, evaluate, waitFor, reloadPage }) => {
    await evaluate(`document.getElementById('mode-opt-edit').click();document.getElementById('toggle-library-btn').click();
        window.originalConfirm=window.confirm;window.allowBulkConfirm=false;window.bulkQuestions=[];
        window.confirm=message=>{bulkQuestions.push(message);return allowBulkConfirm};
        document.getElementById('library-search').value='Page 1';document.getElementById('library-search').dispatchEvent(new Event('input'));`);
    await waitFor(`document.querySelectorAll('#backgrounds-grid .media-item').length===11`);
    await evaluate(`document.querySelector('[data-select-library="backgrounds"]').click()`);
    assert.equal(await evaluate(`document.getElementById('library-selection-count').textContent`),'49 selected');
    const before = await evaluate(`document.querySelectorAll('#layer-list > *').length`);
    await evaluate(`document.getElementById('library-destination').value='foregrounds';document.getElementById('library-move').click();document.getElementById('library-remove').click()`);
    assert.equal(await evaluate(`bulkQuestions.length`),2);
    assert.ok(await evaluate(`bulkQuestions.every(text=>text.includes('49')&&text.includes('Backgrounds'))`));
    assert.equal(await evaluate(`document.querySelectorAll('#layer-list > *').length`),before);
    assert.equal(await evaluate(`document.getElementById('backgrounds-count').textContent`),'49');
    assert.equal(await evaluate(`document.getElementById('library-selection-count').textContent`),'49 selected');
    console.log('PASS: per-pane select-all spans pages and filters; cancelling Move and Delete leaves state and selection intact');
    await evaluate(`allowBulkConfirm=true;document.getElementById('library-add-canvas').click()`);
    await waitFor(`document.querySelectorAll('#layer-list > *').length===${before+49}`);
    await evaluate(`document.getElementById('undo-btn').click()`);
    assert.equal(await evaluate(`document.querySelectorAll('#layer-list > *').length`),before);
    await evaluate(`document.getElementById('redo-btn').click()`);
    assert.equal(await evaluate(`document.querySelectorAll('#layer-list > *').length`),before+49);
    await evaluate(`document.getElementById('library-search').value='';document.getElementById('library-search').dispatchEvent(new Event('input'))`);
    await waitFor(`document.querySelector('#visual-targets-grid video')`);
    await evaluate(`document.querySelector('#visual-targets-grid video').parentElement.querySelector('.library-select').click();document.getElementById('library-add-canvas').click()`);
    await waitFor(`document.querySelectorAll('#layer-list > *').length===${before+50}`);
    await evaluate(`(async()=>{for(let n=0;n<6&&!document.querySelector('.save-slot__btn--save[data-slot="3"]');n++)await (async()=>{document.getElementById('add-save-slot')?.click();await new Promise(r=>setTimeout(r,120))})(); document.querySelector('.save-slot__btn--save[data-slot="3"]').click()})()`);
    await waitFor(`document.querySelector('.save-slot__btn--load[data-slot="3"]')`);
    const saved = await evaluate(`new Promise(resolve=>{const r=indexedDB.open('gazeTrackerSaves');r.onsuccess=()=>{const db=r.result;const q=db.transaction('slots').objectStore('slots').get(3);q.onsuccess=()=>{resolve(q.result);db.close()}}})`);
    assert.equal(saved.objects.length,before+50);
    assert.ok(saved.objects.filter(o=>o.type==='image').every(o=>o.imgSrc.startsWith('data:')));
    assert.ok(saved.objects.some(o=>o.type==='video'&&o.videoSrc.startsWith('data:video/')));
    console.log('PASS: image/video batches without an extra confirmation add separate targets, undo in one step, and save original media');
    await evaluate(`document.querySelector('[data-select-library="backgrounds"]').click();window.decodeBeforeFailure=MediaStore.decode;MediaStore.decode=async()=>{throw new Error('Simulated decode failure')};document.getElementById('library-add-canvas').click()`);
    await waitFor(`document.getElementById('library-status').textContent.includes('Simulated decode failure')`);
    assert.equal(await evaluate(`document.querySelectorAll('#layer-list > *').length`),before+50);
    assert.equal(await evaluate(`document.getElementById('library-selection-count').textContent`),'49 selected');
    await evaluate(`MediaStore.decode=decodeBeforeFailure;document.getElementById('library-destination').value='foregrounds';document.getElementById('library-move').click()`);
    await waitFor(`document.getElementById('foregrounds-count').textContent==='49'`);
    assert.equal(await evaluate(`document.getElementById('backgrounds-count').textContent`),'');
    await evaluate(`document.querySelector('[data-select-library="foregrounds"]').click();document.getElementById('library-organize').scrollIntoView({block:'end',behavior:'instant'})`);
    await new Promise(r=>setTimeout(r,350));
    assert.equal(await evaluate(`getComputedStyle(document.getElementById('foregrounds-grid')).gridTemplateColumns.split(' ').length`),await evaluate(`matchMedia('(any-pointer: coarse)').matches ? 2 : 3`));
    await evaluate(`document.querySelectorAll('.toast').forEach(el=>el.remove())`);
    await command('Page.captureScreenshot').then(r=>fs.writeFileSync(require('./screenshot-path.cjs')('library-bulk-mobile.png'),Buffer.from(r.data,'base64')));
    await evaluate(`document.getElementById('library-remove').click()`);
    await waitFor(`document.getElementById('foregrounds-count').textContent===''`);
    await evaluate(`window.confirm=originalConfirm`);
    await reloadPage();
    await waitFor(`document.getElementById('library-status')?.dataset.ready==='true'`);
    assert.equal(await evaluate(`document.getElementById('foregrounds-count').textContent`),'');
    await evaluate(`document.querySelector('.save-slot__btn--load[data-slot="3"]').click()`);
    await waitFor(`document.querySelectorAll('#layer-list > *').length===${before+50}`);
    console.log('PASS: failed bulk decoding adds nothing; confirmed moves/deletes persist and saved canvas media survives deletion');
};
