const assert = require('node:assert/strict');
const fs = require('node:fs');

module.exports = async ({ command, evaluate, waitFor, reloadPage }) => {
    await command('Emulation.setDeviceMetricsOverride', { width:1280,height:900,deviceScaleFactor:1,mobile:false });
    await waitFor(`!document.getElementById('splash-screen-overlay')`);
    const readSlot = `window.readTestSlot ||= slot => new Promise(resolve=>{const r=indexedDB.open('gazeTrackerSaves');r.onsuccess=()=>{const db=r.result;const q=db.transaction('slots').objectStore('slots').get(slot);q.onsuccess=()=>{resolve(q.result);db.close()}}});`;
    // Start with a legacy save that has no dragging preference.
    await evaluate(`${readSlot} (async()=>{
        const scene=await readTestSlot(2); scene.objects=scene.objects.filter(o=>o.type==='image').slice(0,1);
        Object.assign(scene.objects[0],{x:500,y:300,width:160,height:160,animationType:'gentle-shake',animationDuration:.5,animationCycles:1,animationIntensity:10,triggerOnPress:true,speechMode:'none'});
        delete scene.objects[0].allowPlayDrag;
        Object.assign(scene,{backgroundImage:null,foregroundImage:null,canvasZoom:.5,canvasPanX:20,canvasPanY:20,showGuides:false,enableHoverPopup:false});
        await new Promise(resolve=>{const r=indexedDB.open('gazeTrackerSaves');r.onsuccess=()=>{const db=r.result;const tx=db.transaction('slots','readwrite');tx.objectStore('slots').put(scene);tx.oncomplete=()=>{db.close();resolve()}}});
        document.querySelector('.save-slot__btn--load[data-slot="2"]').click();
    })()`);
    await waitFor(`document.querySelectorAll('#layer-list > *').length === 1`);
    const pointer = (type,x,y,buttons=0) => command('Input.dispatchMouseEvent',{type,x,y,button:type==='mouseMoved'?'none':'left',buttons,clickCount:1});
    const tap = async (x,y) => { await pointer('mousePressed',x,y,1); await pointer('mouseReleased',x,y); };
    const drag = async (x,y,dx,dy) => { await pointer('mousePressed',x,y,1); await pointer('mouseMoved',x+dx,y+dy,1); await pointer('mouseReleased',x+dx,y+dy); };
    const saveScene = async () => {
        await evaluate(`${readSlot} (async()=>{ window.lastTestSave = (await readTestSlot(2)).savedAt; document.querySelector('.save-slot__btn--save[data-slot="2"]').click(); })()`);
        await waitFor(`readTestSlot(2).then(row=>row.savedAt !== lastTestSave)`);
        return evaluate(`readTestSlot(2)`);
    };
    await evaluate(`document.getElementById('mode-opt-edit').click()`);
    assert.equal(await evaluate(`document.getElementById('mode-opt-edit').getAttribute('aria-pressed')`),'true');
    await evaluate(`document.getElementById('mode-opt-play').click()`);
    await waitFor(`document.body.classList.contains('panels-hidden')`);
    assert.ok(await evaluate(`!document.querySelector('.drawer.open') && getComputedStyle(document.getElementById('animation-panel')).display==='none'`));
    const beforePlay = await evaluate(`document.getElementById('main-canvas').toDataURL()`);
    await drag(310,210,60,40);
    await command('Input.dispatchMouseEvent',{type:'mouseWheel',x:400,y:400,deltaX:0,deltaY:-150});
    await evaluate(`for(const key of ['Delete','g','z']) document.getElementById('main-canvas').dispatchEvent(new KeyboardEvent('keydown',{key,ctrlKey:key==='z',bubbles:true,cancelable:true}));
        const el=document.getElementById('canvas-container');
        el.dispatchEvent(new MouseEvent('mousedown',{button:1,clientX:400,clientY:400,bubbles:true}));
        window.dispatchEvent(new MouseEvent('mousemove',{clientX:450,clientY:450,bubbles:true}));
        window.dispatchEvent(new MouseEvent('mouseup',{bubbles:true}));
        const touches=[new Touch({identifier:1,target:el,clientX:400,clientY:400}),new Touch({identifier:2,target:el,clientX:500,clientY:500})];
        el.dispatchEvent(new TouchEvent('touchstart',{touches,bubbles:true,cancelable:true}));
        el.dispatchEvent(new TouchEvent('touchmove',{touches:[touches[0],new Touch({identifier:2,target:el,clientX:650,clientY:650})],bubbles:true,cancelable:true}));
        el.dispatchEvent(new TouchEvent('touchend',{touches:[],changedTouches:[touches[0]],bubbles:true}));
        el.dispatchEvent(new TouchEvent('touchend',{touches:[],changedTouches:[touches[0]],bubbles:true}));`);
    const locked = await saveScene();
    assert.equal(locked.objects.length,1); assert.equal(locked.objects[0].x,500); assert.equal(locked.objects[0].y,300);
    assert.equal(locked.objects[0].allowPlayDrag,false); assert.equal(locked.canvasZoom,.5); assert.equal(locked.canvasPanX,20); assert.equal(locked.canvasPanY,20);
    assert.equal(await evaluate(`document.getElementById('main-canvas').toDataURL()`),beforePlay,'Locked drag must not accidentally animate');
    await tap(310,210);
    await waitFor(`document.getElementById('main-canvas').toDataURL() !== ${JSON.stringify(beforePlay)}`);
    await new Promise(resolve=>setTimeout(resolve,650));
    console.log('PASS: Play hides panels, locks targets and canvas gestures, blocks edit shortcuts, and keeps tap animation');
    await evaluate(`document.getElementById('toggle-controls-btn').click(); document.getElementById('mode-opt-edit').click()`);
    // Close the drawer without selecting another target, then select on the canvas.
    await evaluate(`for (const [drawer, handle] of [['controls-drawer','toggle-controls-btn'],['media-library','toggle-library-btn']]) { if (document.getElementById(drawer).classList.contains('open')) document.getElementById(handle).click(); }`);
    await new Promise(resolve=>setTimeout(resolve,350));
    await tap(310,210);
    assert.equal(await evaluate(`document.getElementById('play-drag-setting').hidden`),false);
    await evaluate(`document.getElementById('allow-play-drag').click()`);
    await saveScene();
    await evaluate(`document.getElementById('mode-opt-play').click()`);
    await drag(310,210,60,40);
    const unlocked = await saveScene();
    assert.equal(unlocked.objects[0].allowPlayDrag,true);
    assert.equal(unlocked.objects[0].x,620); assert.equal(unlocked.objects[0].y,380);
    assert.equal(unlocked.objects[0].width,160); assert.equal(unlocked.objects[0].height,160);
    await evaluate(`document.getElementById('mode-opt-edit').click(); document.getElementById('undo-btn').click()`);
    const undone = await saveScene();
    assert.equal(undone.objects[0].x,500); assert.equal(undone.objects[0].allowPlayDrag,true);
    await reloadPage();
    await waitFor(`document.querySelector('.save-slot__btn--load[data-slot="2"]')`);
    await evaluate(`document.getElementById('splash-close-btn').click();document.querySelector('.save-slot__btn--load[data-slot="2"]').click()`);
    await waitFor(`document.querySelectorAll('#layer-list > *').length===1`);
    await waitFor(`!document.getElementById('splash-screen-overlay')`);
    await evaluate(`document.getElementById('mode-opt-play').click()`);
    await drag(310,210,30,20);
    const restored = await saveScene();
    assert.equal(restored.objects[0].allowPlayDrag,true); assert.equal(restored.objects[0].x,560); assert.equal(restored.objects[0].y,340);
    await command('Page.captureScreenshot').then(result=>fs.writeFileSync(require('./screenshot-path.cjs')('canvas-play.png'),Buffer.from(result.data,'base64')));
    console.log('PASS: optional Play dragging translates without resizing, can be undone, and survives save/reload');
    await command('Emulation.setDeviceMetricsOverride', { width:390,height:844,deviceScaleFactor:1,mobile:true });
    const mobile = await saveScene();
    const target = mobile.objects[0];
    const x=(target.x+target.width/2)*mobile.canvasZoom+mobile.canvasPanX;
    const y=(target.y+target.height/2)*mobile.canvasZoom+mobile.canvasPanY;
    await command('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});
    await command('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+15,y:y+15}]});
    await command('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
    const touched = await saveScene();
    assert.ok(Math.abs(touched.objects[0].x-target.x-15/mobile.canvasZoom)<.01);
    assert.equal(touched.objects[0].width,target.width);
    console.log('PASS: native touch dragging works in mobile Play without resizing');

    // A last page with just one image must have exactly the same navigation position.
    await evaluate(`document.getElementById('mode-opt-edit').click(); document.getElementById('toggle-library-btn').click();
        const t=new DataTransfer();
        for(let i=0;i<49;i++)t.items.add(new File(['<svg xmlns="http://www.w3.org/2000/svg" width="30" height="30"><circle cx="15" cy="15" r="'+(i/4+1)+'"/></svg>'],'Page '+i+'.svg',{type:'image/svg+xml'}));
        const input=document.getElementById('bg-image-input');input.files=t.files;input.dispatchEvent(new Event('change'));`);
    await waitFor(`document.getElementById('backgrounds-count').textContent==='49'`);
    await new Promise(resolve=>setTimeout(resolve,350));
    assert.ok(await evaluate(`(() => {
        const nav=document.getElementById('library-page-backgrounds');
        const button=nav.querySelector('button:last-child');
        nav.scrollIntoView({block:'center',behavior:'instant'});
        const before=button.getBoundingClientRect(); button.click();
        const after=button.getBoundingClientRect();
        return before.y===after.y && before.x===after.x && document.querySelectorAll('#backgrounds-grid .media-item').length===1;
    })()`));
    console.log('PASS: single-image last page keeps pagination fixed on mobile');
    assert.ok(await evaluate(`document.getElementById('install-app-btn').closest('.display-controls') !== null`));
};
